### ISSUE TITLE
Getting 404 if send access_token with request.

### ISSUE THREAD

**Issue by nikmish1** [arocketman/Spring-oauth2-jpa-example#2]
Hi Arocketman

Thanks for the sample application its of great help. But I am facing a problem. I have successfully generated the token but while send request to protected resource with access token it gives me 404 not found.Can you please look at the issue.

{
    "timestamp": 1499576683397,
    "status": 404,
    "error": "Not Found",
    "message": "No message available",
    "path": "/private"
}

**Comment by arocketman** [comment]
Hello,
there could be several reasons for this particular problem. Would you please post a link to a repository containing your code? 

If you want to figure out the problem, you could try:

- Fork this repository
- Run the example
- Compare your code with the repository one and figure out what the difference is

**Comment by nikmish1** [comment]
Thanks for prompt response . 
When I run your example I am facing the same issue -
{
    "timestamp": 1499588906543,
    "status": 404,
    "error": "Not Found",
    "message": "No message available",
    "path": "/private/"
}

**Comment by nikmish1** [comment]
Hi 

I have updated the issue on stackoverflow

https://stackoverflow.com/questions/44994726/spring-boot-oauth2-getting-404-while-accessing-protected-resource-with-access-to

**Comment by arocketman** [comment]
Seems like you solved your problem, based on the stackoverflow link?

**Comment by nikmish1** [comment]
Yes the issue is resolved .  It was my mistake I forgot to add trailing
Slash.

**Comment by arocketman** [comment]
Very well!
