### ISSUE TITLE
Please mentioned steps to execute the code

### ISSUE THREAD

**Issue by JavaNeed** [arocketman/Spring-oauth2-jpa-example#3]
Please mentioned steps to execute the code

I can simply call the  curl -i http://localhost:8080/
so where is the security ?

**Comment by arocketman** [comment]
http.headers().frameOptions().disable().and()
                .authorizeRequests()
                .antMatchers("/","/home","/register","/login").permitAll()
                .antMatchers("/private/**").authenticated();

As you can see from this code from the ResourceServerConfig class the "/" path isn't secured. Only the /private/* path is. 

Hence the steps you mention result in a correct response.
