### ISSUE TITLE
/private RequestMapping isnt configured in HomeController

### ISSUE THREAD

**Issue by ninadpchaudhari** [arocketman/Spring-oauth2-jpa-example#4]
As mentioned in the Video at :
https://youtu.be/0pD7YeTAUkk?t=2m41s

There should be a resource that is private and requires auth.

**Comment by arocketman** [comment]
Thanks for opening the issue. Indeed the privateArea mapping was missing in the repo as seen in the video. 
Fixed it in : https://github.com/arocketman/Spring-oauth2-jpa-example/commit/8c1d17e320ea3be76f941d39da48d99b976b9773
