### ISSUE TITLE
How to migrate to Spring Boot 2.0.0

### ISSUE THREAD

**Issue by nats-afs** [arocketman/Spring-oauth2-jpa-example#5]
I'm novice using Spring Boot.
Your sample project works on Spring Boot 1.5.x
But when trying running on 2.0.0 throws this: 

Description:

Field authenticationManager in com.mh.sgmun.configuration.AuthorizationServerConfiguration required a bean of type 'org.springframework.security.authentication.AuthenticationManager' that could not be found.

Action:

Consider defining a bean of type 'org.springframework.security.authentication.AuthenticationManager' in your configuration.

**Comment by arocketman** [comment]
Hopefully this is solved thanks to @Tonnix contribution with commit #6
