### ISSUE TITLE
Add video link in the README

### ISSUE THREAD

**Issue by sol-andrehil** [arocketman/Spring-oauth2-jpa-example#7]
I found this repo through Google and I wasn't aware that there is a video for it (found the link in a closed issue).
I think it would be nice to add the link to README, so people who find it like me will know about it.

**Comment by siki1793** [comment]
https://www.youtube.com/watch?v=0pD7YeTAUkk&list=PLaCuXAAp7BL2nVYTAY0Oy9jSuCRdip_Iy&index=2

**Comment by arocketman** [comment]
Done! Thanks for your comment.
